// Code generated by gocc; DO NOT EDIT.

package lexer

import (
	"io/ioutil"
	"unicode/utf8"

	"github.com/teslamotors/jsonql/token"
)

const (
	NoState    = -1
	NumStates  = 114
	NumSymbols = 110
)

type Lexer struct {
	src    []byte
	pos    int
	line   int
	column int
}

func NewLexer(src []byte) *Lexer {
	lexer := &Lexer{
		src:    src,
		pos:    0,
		line:   1,
		column: 1,
	}
	return lexer
}

func NewLexerFile(fpath string) (*Lexer, error) {
	src, err := ioutil.ReadFile(fpath)
	if err != nil {
		return nil, err
	}
	return NewLexer(src), nil
}

func (l *Lexer) Scan() (tok *token.Token) {
	tok = new(token.Token)
	if l.pos >= len(l.src) {
		tok.Type = token.EOF
		tok.Pos.Offset, tok.Pos.Line, tok.Pos.Column = l.pos, l.line, l.column
		return
	}
	start, startLine, startColumn, end := l.pos, l.line, l.column, 0
	tok.Type = token.INVALID
	state, rune1, size := 0, rune(-1), 0
	for state != -1 {
		if l.pos >= len(l.src) {
			rune1 = -1
		} else {
			rune1, size = utf8.DecodeRune(l.src[l.pos:])
			l.pos += size
		}

		nextState := -1
		if rune1 != -1 {
			nextState = TransTab[state](rune1)
		}
		state = nextState

		if state != -1 {

			switch rune1 {
			case '\n':
				l.line++
				l.column = 1
			case '\r':
				l.column = 1
			case '\t':
				l.column += 4
			default:
				l.column++
			}

			switch {
			case ActTab[state].Accept != -1:
				tok.Type = ActTab[state].Accept
				end = l.pos
			case ActTab[state].Ignore != "":
				start, startLine, startColumn = l.pos, l.line, l.column
				state = 0
				if start >= len(l.src) {
					tok.Type = token.EOF
				}

			}
		} else {
			if tok.Type == token.INVALID {
				end = l.pos
			}
		}
	}
	if end > start {
		l.pos = end
		tok.Lit = l.src[start:end]
	} else {
		tok.Lit = []byte{}
	}
	tok.Pos.Offset, tok.Pos.Line, tok.Pos.Column = start, startLine, startColumn

	return
}

func (l *Lexer) Reset() {
	l.pos = 0
}

/*
Lexer symbols:
0: '_'
1: '.'
2: '.'
3: '"'
4: '\'
5: '"'
6: '"'
7: '''
8: '\'
9: '''
10: '''
11: '|'
12: '|'
13: '&'
14: '&'
15: '='
16: '='
17: '='
18: '!'
19: '='
20: '<'
21: '='
22: '>'
23: '='
24: '>'
25: '<'
26: 'i'
27: 's'
28: 'i'
29: 's'
30: 'n'
31: 'o'
32: 't'
33: 'n'
34: 'o'
35: 't'
36: 'n'
37: 'u'
38: 'l'
39: 'l'
40: 'd'
41: 'e'
42: 'f'
43: 'i'
44: 'n'
45: 'e'
46: 'd'
47: '~'
48: '='
49: '!'
50: '~'
51: '='
52: '+'
53: '-'
54: '*'
55: '/'
56: '%'
57: '^'
58: '!'
59: 't'
60: 'r'
61: 'u'
62: 'e'
63: 'f'
64: 'a'
65: 'l'
66: 's'
67: 'e'
68: '.'
69: '['
70: ']'
71: '_'
72: 'e'
73: 'E'
74: '+'
75: '-'
76: '0'
77: '0'
78: 'x'
79: 'X'
80: '\'
81: 'x'
82: '\'
83: 'u'
84: 'b'
85: 'f'
86: 'n'
87: 'r'
88: 't'
89: 'v'
90: '\'
91: '\'
92: ' '
93: '\t'
94: '\f'
95: '\v'
96: \u00a0
97: \u202f
98: \u205f
99: \u3000
100: \ufeff
101: 'A'-'Z'
102: 'a'-'z'
103: '0'-'9'
104: '1'-'9'
105: '0'-'7'
106: 'a'-'f'
107: 'A'-'F'
108: \u2000-\u200a
109: .
*/
