// Code generated by gocc; DO NOT EDIT.

package lexer

/*
Let s be the current state
Let r be the current input rune
transitionTable[s](r) returns the next state.
*/
type TransitionTable [NumStates]func(rune) int

var TransTab = TransitionTable{
	// S0
	func(r rune) int {
		switch {
		case r == 9: // ['\t','\t']
			return 1
		case r == 11: // ['\v','\v']
			return 1
		case r == 12: // ['\f','\f']
			return 1
		case r == 32: // [' ',' ']
			return 1
		case r == 33: // ['!','!']
			return 2
		case r == 34: // ['"','"']
			return 3
		case r == 37: // ['%','%']
			return 4
		case r == 39: // [''',''']
			return 5
		case r == 42: // ['*','*']
			return 6
		case r == 45: // ['-','-']
			return 7
		case r == 46: // ['.','.']
			return 8
		case r == 47: // ['/','/']
			return 9
		case r == 48: // ['0','0']
			return 10
		case 49 <= r && r <= 57: // ['1','9']
			return 11
		case 65 <= r && r <= 90: // ['A','Z']
			return 12
		case r == 91: // ['[','[']
			return 13
		case r == 93: // [']',']']
			return 14
		case r == 94: // ['^','^']
			return 15
		case r == 95: // ['_','_']
			return 16
		case 97 <= r && r <= 101: // ['a','e']
			return 12
		case r == 102: // ['f','f']
			return 17
		case 103 <= r && r <= 109: // ['g','m']
			return 12
		case r == 110: // ['n','n']
			return 18
		case 111 <= r && r <= 115: // ['o','s']
			return 12
		case r == 116: // ['t','t']
			return 19
		case 117 <= r && r <= 122: // ['u','z']
			return 12
		case r == 160: // [\u00a0,\u00a0]
			return 1
		case 8192 <= r && r <= 8202: // [\u2000,\u200a]
			return 1
		case r == 8239: // [\u202f,\u202f]
			return 1
		case r == 8287: // [\u205f,\u205f]
			return 1
		case r == 12288: // [\u3000,\u3000]
			return 1
		case r == 65279: // [\ufeff,\ufeff]
			return 1
		}
		return NoState
	},
	// S1
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S2
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S3
	func(r rune) int {
		switch {
		case r == 34: // ['"','"']
			return 20
		case r == 92: // ['\','\']
			return 21
		default:
			return 3
		}
	},
	// S4
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S5
	func(r rune) int {
		switch {
		case r == 39: // [''',''']
			return 22
		case r == 92: // ['\','\']
			return 23
		default:
			return 5
		}
	},
	// S6
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S7
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S8
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 24
		}
		return NoState
	},
	// S9
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S10
	func(r rune) int {
		switch {
		case r == 46: // ['.','.']
			return 25
		case 48 <= r && r <= 55: // ['0','7']
			return 26
		case 56 <= r && r <= 57: // ['8','9']
			return 27
		case r == 69: // ['E','E']
			return 28
		case r == 88: // ['X','X']
			return 29
		case r == 101: // ['e','e']
			return 28
		case r == 120: // ['x','x']
			return 29
		}
		return NoState
	},
	// S11
	func(r rune) int {
		switch {
		case r == 46: // ['.','.']
			return 25
		case 48 <= r && r <= 57: // ['0','9']
			return 11
		case r == 69: // ['E','E']
			return 28
		case r == 101: // ['e','e']
			return 28
		}
		return NoState
	},
	// S12
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 30
		case 65 <= r && r <= 90: // ['A','Z']
			return 31
		case r == 95: // ['_','_']
			return 32
		case 97 <= r && r <= 122: // ['a','z']
			return 31
		}
		return NoState
	},
	// S13
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S14
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S15
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S16
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 30
		case 65 <= r && r <= 90: // ['A','Z']
			return 31
		case r == 95: // ['_','_']
			return 32
		case 97 <= r && r <= 122: // ['a','z']
			return 31
		}
		return NoState
	},
	// S17
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 30
		case 65 <= r && r <= 90: // ['A','Z']
			return 31
		case r == 95: // ['_','_']
			return 32
		case r == 97: // ['a','a']
			return 33
		case 98 <= r && r <= 122: // ['b','z']
			return 31
		}
		return NoState
	},
	// S18
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 30
		case 65 <= r && r <= 90: // ['A','Z']
			return 31
		case r == 95: // ['_','_']
			return 32
		case 97 <= r && r <= 116: // ['a','t']
			return 31
		case r == 117: // ['u','u']
			return 34
		case 118 <= r && r <= 122: // ['v','z']
			return 31
		}
		return NoState
	},
	// S19
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 30
		case 65 <= r && r <= 90: // ['A','Z']
			return 31
		case r == 95: // ['_','_']
			return 32
		case 97 <= r && r <= 113: // ['a','q']
			return 31
		case r == 114: // ['r','r']
			return 35
		case 115 <= r && r <= 122: // ['s','z']
			return 31
		}
		return NoState
	},
	// S20
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S21
	func(r rune) int {
		switch {
		case r == 34: // ['"','"']
			return 3
		case r == 92: // ['\','\']
			return 36
		case r == 98: // ['b','b']
			return 36
		case r == 102: // ['f','f']
			return 36
		case r == 110: // ['n','n']
			return 36
		case r == 114: // ['r','r']
			return 36
		case r == 116: // ['t','t']
			return 36
		case r == 117: // ['u','u']
			return 37
		case r == 118: // ['v','v']
			return 36
		case r == 120: // ['x','x']
			return 38
		}
		return NoState
	},
	// S22
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S23
	func(r rune) int {
		switch {
		case r == 39: // [''',''']
			return 5
		case r == 92: // ['\','\']
			return 39
		case r == 98: // ['b','b']
			return 39
		case r == 102: // ['f','f']
			return 39
		case r == 110: // ['n','n']
			return 39
		case r == 114: // ['r','r']
			return 39
		case r == 116: // ['t','t']
			return 39
		case r == 117: // ['u','u']
			return 40
		case r == 118: // ['v','v']
			return 39
		case r == 120: // ['x','x']
			return 41
		}
		return NoState
	},
	// S24
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 24
		case r == 69: // ['E','E']
			return 42
		case r == 101: // ['e','e']
			return 42
		}
		return NoState
	},
	// S25
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 43
		case r == 69: // ['E','E']
			return 44
		case r == 101: // ['e','e']
			return 44
		}
		return NoState
	},
	// S26
	func(r rune) int {
		switch {
		case r == 46: // ['.','.']
			return 25
		case 48 <= r && r <= 55: // ['0','7']
			return 26
		case 56 <= r && r <= 57: // ['8','9']
			return 27
		case r == 69: // ['E','E']
			return 28
		case r == 101: // ['e','e']
			return 28
		}
		return NoState
	},
	// S27
	func(r rune) int {
		switch {
		case r == 46: // ['.','.']
			return 25
		case 48 <= r && r <= 57: // ['0','9']
			return 27
		case r == 69: // ['E','E']
			return 28
		case r == 101: // ['e','e']
			return 28
		}
		return NoState
	},
	// S28
	func(r rune) int {
		switch {
		case r == 43: // ['+','+']
			return 45
		case r == 45: // ['-','-']
			return 45
		case 48 <= r && r <= 57: // ['0','9']
			return 46
		}
		return NoState
	},
	// S29
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 47
		case 65 <= r && r <= 70: // ['A','F']
			return 48
		case 97 <= r && r <= 102: // ['a','f']
			return 48
		}
		return NoState
	},
	// S30
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 30
		case 65 <= r && r <= 90: // ['A','Z']
			return 31
		case r == 95: // ['_','_']
			return 32
		case 97 <= r && r <= 122: // ['a','z']
			return 31
		}
		return NoState
	},
	// S31
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 30
		case 65 <= r && r <= 90: // ['A','Z']
			return 31
		case r == 95: // ['_','_']
			return 32
		case 97 <= r && r <= 122: // ['a','z']
			return 31
		}
		return NoState
	},
	// S32
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 30
		case 65 <= r && r <= 90: // ['A','Z']
			return 31
		case r == 95: // ['_','_']
			return 32
		case 97 <= r && r <= 122: // ['a','z']
			return 31
		}
		return NoState
	},
	// S33
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 30
		case 65 <= r && r <= 90: // ['A','Z']
			return 31
		case r == 95: // ['_','_']
			return 32
		case 97 <= r && r <= 107: // ['a','k']
			return 31
		case r == 108: // ['l','l']
			return 49
		case 109 <= r && r <= 122: // ['m','z']
			return 31
		}
		return NoState
	},
	// S34
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 30
		case 65 <= r && r <= 90: // ['A','Z']
			return 31
		case r == 95: // ['_','_']
			return 32
		case 97 <= r && r <= 107: // ['a','k']
			return 31
		case r == 108: // ['l','l']
			return 50
		case 109 <= r && r <= 122: // ['m','z']
			return 31
		}
		return NoState
	},
	// S35
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 30
		case 65 <= r && r <= 90: // ['A','Z']
			return 31
		case r == 95: // ['_','_']
			return 32
		case 97 <= r && r <= 116: // ['a','t']
			return 31
		case r == 117: // ['u','u']
			return 51
		case 118 <= r && r <= 122: // ['v','z']
			return 31
		}
		return NoState
	},
	// S36
	func(r rune) int {
		switch {
		case r == 34: // ['"','"']
			return 20
		case r == 92: // ['\','\']
			return 21
		default:
			return 3
		}
	},
	// S37
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 52
		case 65 <= r && r <= 70: // ['A','F']
			return 53
		case 97 <= r && r <= 102: // ['a','f']
			return 53
		}
		return NoState
	},
	// S38
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 54
		case 65 <= r && r <= 70: // ['A','F']
			return 55
		case 97 <= r && r <= 102: // ['a','f']
			return 55
		}
		return NoState
	},
	// S39
	func(r rune) int {
		switch {
		case r == 39: // [''',''']
			return 22
		case r == 92: // ['\','\']
			return 23
		default:
			return 5
		}
	},
	// S40
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 56
		case 65 <= r && r <= 70: // ['A','F']
			return 57
		case 97 <= r && r <= 102: // ['a','f']
			return 57
		}
		return NoState
	},
	// S41
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 58
		case 65 <= r && r <= 70: // ['A','F']
			return 59
		case 97 <= r && r <= 102: // ['a','f']
			return 59
		}
		return NoState
	},
	// S42
	func(r rune) int {
		switch {
		case r == 43: // ['+','+']
			return 60
		case r == 45: // ['-','-']
			return 60
		case 48 <= r && r <= 57: // ['0','9']
			return 61
		}
		return NoState
	},
	// S43
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 43
		case r == 69: // ['E','E']
			return 44
		case r == 101: // ['e','e']
			return 44
		}
		return NoState
	},
	// S44
	func(r rune) int {
		switch {
		case r == 43: // ['+','+']
			return 62
		case r == 45: // ['-','-']
			return 62
		case 48 <= r && r <= 57: // ['0','9']
			return 63
		}
		return NoState
	},
	// S45
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 46
		}
		return NoState
	},
	// S46
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 46
		}
		return NoState
	},
	// S47
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 47
		case 65 <= r && r <= 70: // ['A','F']
			return 48
		case 97 <= r && r <= 102: // ['a','f']
			return 48
		}
		return NoState
	},
	// S48
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 47
		case 65 <= r && r <= 70: // ['A','F']
			return 48
		case 97 <= r && r <= 102: // ['a','f']
			return 48
		}
		return NoState
	},
	// S49
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 30
		case 65 <= r && r <= 90: // ['A','Z']
			return 31
		case r == 95: // ['_','_']
			return 32
		case 97 <= r && r <= 114: // ['a','r']
			return 31
		case r == 115: // ['s','s']
			return 64
		case 116 <= r && r <= 122: // ['t','z']
			return 31
		}
		return NoState
	},
	// S50
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 30
		case 65 <= r && r <= 90: // ['A','Z']
			return 31
		case r == 95: // ['_','_']
			return 32
		case 97 <= r && r <= 107: // ['a','k']
			return 31
		case r == 108: // ['l','l']
			return 65
		case 109 <= r && r <= 122: // ['m','z']
			return 31
		}
		return NoState
	},
	// S51
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 30
		case 65 <= r && r <= 90: // ['A','Z']
			return 31
		case r == 95: // ['_','_']
			return 32
		case 97 <= r && r <= 100: // ['a','d']
			return 31
		case r == 101: // ['e','e']
			return 66
		case 102 <= r && r <= 122: // ['f','z']
			return 31
		}
		return NoState
	},
	// S52
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 67
		case 65 <= r && r <= 70: // ['A','F']
			return 68
		case 97 <= r && r <= 102: // ['a','f']
			return 68
		}
		return NoState
	},
	// S53
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 67
		case 65 <= r && r <= 70: // ['A','F']
			return 68
		case 97 <= r && r <= 102: // ['a','f']
			return 68
		}
		return NoState
	},
	// S54
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 69
		case 65 <= r && r <= 70: // ['A','F']
			return 70
		case 97 <= r && r <= 102: // ['a','f']
			return 70
		}
		return NoState
	},
	// S55
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 69
		case 65 <= r && r <= 70: // ['A','F']
			return 70
		case 97 <= r && r <= 102: // ['a','f']
			return 70
		}
		return NoState
	},
	// S56
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 71
		case 65 <= r && r <= 70: // ['A','F']
			return 72
		case 97 <= r && r <= 102: // ['a','f']
			return 72
		}
		return NoState
	},
	// S57
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 71
		case 65 <= r && r <= 70: // ['A','F']
			return 72
		case 97 <= r && r <= 102: // ['a','f']
			return 72
		}
		return NoState
	},
	// S58
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 73
		case 65 <= r && r <= 70: // ['A','F']
			return 74
		case 97 <= r && r <= 102: // ['a','f']
			return 74
		}
		return NoState
	},
	// S59
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 73
		case 65 <= r && r <= 70: // ['A','F']
			return 74
		case 97 <= r && r <= 102: // ['a','f']
			return 74
		}
		return NoState
	},
	// S60
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 61
		}
		return NoState
	},
	// S61
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 61
		}
		return NoState
	},
	// S62
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 63
		}
		return NoState
	},
	// S63
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 63
		}
		return NoState
	},
	// S64
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 30
		case 65 <= r && r <= 90: // ['A','Z']
			return 31
		case r == 95: // ['_','_']
			return 32
		case 97 <= r && r <= 100: // ['a','d']
			return 31
		case r == 101: // ['e','e']
			return 75
		case 102 <= r && r <= 122: // ['f','z']
			return 31
		}
		return NoState
	},
	// S65
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 30
		case 65 <= r && r <= 90: // ['A','Z']
			return 31
		case r == 95: // ['_','_']
			return 32
		case 97 <= r && r <= 122: // ['a','z']
			return 31
		}
		return NoState
	},
	// S66
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 30
		case 65 <= r && r <= 90: // ['A','Z']
			return 31
		case r == 95: // ['_','_']
			return 32
		case 97 <= r && r <= 122: // ['a','z']
			return 31
		}
		return NoState
	},
	// S67
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 76
		case 65 <= r && r <= 70: // ['A','F']
			return 77
		case 97 <= r && r <= 102: // ['a','f']
			return 77
		}
		return NoState
	},
	// S68
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 76
		case 65 <= r && r <= 70: // ['A','F']
			return 77
		case 97 <= r && r <= 102: // ['a','f']
			return 77
		}
		return NoState
	},
	// S69
	func(r rune) int {
		switch {
		case r == 34: // ['"','"']
			return 20
		case r == 92: // ['\','\']
			return 21
		default:
			return 3
		}
	},
	// S70
	func(r rune) int {
		switch {
		case r == 34: // ['"','"']
			return 20
		case r == 92: // ['\','\']
			return 21
		default:
			return 3
		}
	},
	// S71
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 78
		case 65 <= r && r <= 70: // ['A','F']
			return 79
		case 97 <= r && r <= 102: // ['a','f']
			return 79
		}
		return NoState
	},
	// S72
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 78
		case 65 <= r && r <= 70: // ['A','F']
			return 79
		case 97 <= r && r <= 102: // ['a','f']
			return 79
		}
		return NoState
	},
	// S73
	func(r rune) int {
		switch {
		case r == 39: // [''',''']
			return 22
		case r == 92: // ['\','\']
			return 23
		default:
			return 5
		}
	},
	// S74
	func(r rune) int {
		switch {
		case r == 39: // [''',''']
			return 22
		case r == 92: // ['\','\']
			return 23
		default:
			return 5
		}
	},
	// S75
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 30
		case 65 <= r && r <= 90: // ['A','Z']
			return 31
		case r == 95: // ['_','_']
			return 32
		case 97 <= r && r <= 122: // ['a','z']
			return 31
		}
		return NoState
	},
	// S76
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 80
		case 65 <= r && r <= 70: // ['A','F']
			return 81
		case 97 <= r && r <= 102: // ['a','f']
			return 81
		}
		return NoState
	},
	// S77
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 80
		case 65 <= r && r <= 70: // ['A','F']
			return 81
		case 97 <= r && r <= 102: // ['a','f']
			return 81
		}
		return NoState
	},
	// S78
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 82
		case 65 <= r && r <= 70: // ['A','F']
			return 83
		case 97 <= r && r <= 102: // ['a','f']
			return 83
		}
		return NoState
	},
	// S79
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 82
		case 65 <= r && r <= 70: // ['A','F']
			return 83
		case 97 <= r && r <= 102: // ['a','f']
			return 83
		}
		return NoState
	},
	// S80
	func(r rune) int {
		switch {
		case r == 34: // ['"','"']
			return 20
		case r == 92: // ['\','\']
			return 21
		default:
			return 3
		}
	},
	// S81
	func(r rune) int {
		switch {
		case r == 34: // ['"','"']
			return 20
		case r == 92: // ['\','\']
			return 21
		default:
			return 3
		}
	},
	// S82
	func(r rune) int {
		switch {
		case r == 39: // [''',''']
			return 22
		case r == 92: // ['\','\']
			return 23
		default:
			return 5
		}
	},
	// S83
	func(r rune) int {
		switch {
		case r == 39: // [''',''']
			return 22
		case r == 92: // ['\','\']
			return 23
		default:
			return 5
		}
	},
}
