// Code generated by gocc; DO NOT EDIT.

package lexer

/*
Let s be the current state
Let r be the current input rune
transitionTable[s](r) returns the next state.
*/
type TransitionTable [NumStates]func(rune) int

var TransTab = TransitionTable{
	// S0
	func(r rune) int {
		switch {
		case r == 9: // ['\t','\t']
			return 1
		case r == 11: // ['\v','\v']
			return 1
		case r == 12: // ['\f','\f']
			return 1
		case r == 32: // [' ',' ']
			return 1
		case r == 33: // ['!','!']
			return 2
		case r == 34: // ['"','"']
			return 3
		case r == 37: // ['%','%']
			return 4
		case r == 38: // ['&','&']
			return 5
		case r == 39: // [''',''']
			return 6
		case r == 40: // ['(','(']
			return 7
		case r == 41: // [')',')']
			return 8
		case r == 42: // ['*','*']
			return 9
		case r == 43: // ['+','+']
			return 10
		case r == 45: // ['-','-']
			return 11
		case r == 46: // ['.','.']
			return 12
		case r == 47: // ['/','/']
			return 13
		case r == 48: // ['0','0']
			return 14
		case 49 <= r && r <= 57: // ['1','9']
			return 15
		case r == 60: // ['<','<']
			return 16
		case r == 61: // ['=','=']
			return 17
		case r == 62: // ['>','>']
			return 18
		case 65 <= r && r <= 90: // ['A','Z']
			return 19
		case r == 91: // ['[','[']
			return 20
		case r == 93: // [']',']']
			return 21
		case r == 94: // ['^','^']
			return 22
		case r == 95: // ['_','_']
			return 23
		case 97 <= r && r <= 99: // ['a','c']
			return 19
		case r == 100: // ['d','d']
			return 24
		case r == 101: // ['e','e']
			return 19
		case r == 102: // ['f','f']
			return 25
		case 103 <= r && r <= 104: // ['g','h']
			return 19
		case r == 105: // ['i','i']
			return 26
		case 106 <= r && r <= 109: // ['j','m']
			return 19
		case r == 110: // ['n','n']
			return 27
		case 111 <= r && r <= 115: // ['o','s']
			return 19
		case r == 116: // ['t','t']
			return 28
		case 117 <= r && r <= 122: // ['u','z']
			return 19
		case r == 124: // ['|','|']
			return 29
		case r == 126: // ['~','~']
			return 30
		case r == 160: // [\u00a0,\u00a0]
			return 1
		case 8192 <= r && r <= 8202: // [\u2000,\u200a]
			return 1
		case r == 8239: // [\u202f,\u202f]
			return 1
		case r == 8287: // [\u205f,\u205f]
			return 1
		case r == 12288: // [\u3000,\u3000]
			return 1
		case r == 65279: // [\ufeff,\ufeff]
			return 1
		}
		return NoState
	},
	// S1
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S2
	func(r rune) int {
		switch {
		case r == 61: // ['=','=']
			return 31
		case r == 126: // ['~','~']
			return 32
		}
		return NoState
	},
	// S3
	func(r rune) int {
		switch {
		case r == 34: // ['"','"']
			return 33
		case r == 92: // ['\','\']
			return 34
		default:
			return 3
		}
	},
	// S4
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S5
	func(r rune) int {
		switch {
		case r == 38: // ['&','&']
			return 35
		}
		return NoState
	},
	// S6
	func(r rune) int {
		switch {
		case r == 39: // [''',''']
			return 36
		case r == 92: // ['\','\']
			return 37
		default:
			return 6
		}
	},
	// S7
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S8
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S9
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S10
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S11
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S12
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 38
		case r == 91: // ['[','[']
			return 39
		}
		return NoState
	},
	// S13
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S14
	func(r rune) int {
		switch {
		case r == 46: // ['.','.']
			return 40
		case 48 <= r && r <= 55: // ['0','7']
			return 41
		case 56 <= r && r <= 57: // ['8','9']
			return 42
		case r == 69: // ['E','E']
			return 43
		case r == 88: // ['X','X']
			return 44
		case r == 101: // ['e','e']
			return 43
		case r == 120: // ['x','x']
			return 44
		}
		return NoState
	},
	// S15
	func(r rune) int {
		switch {
		case r == 46: // ['.','.']
			return 40
		case 48 <= r && r <= 57: // ['0','9']
			return 15
		case r == 69: // ['E','E']
			return 43
		case r == 101: // ['e','e']
			return 43
		}
		return NoState
	},
	// S16
	func(r rune) int {
		switch {
		case r == 61: // ['=','=']
			return 45
		}
		return NoState
	},
	// S17
	func(r rune) int {
		switch {
		case r == 61: // ['=','=']
			return 46
		}
		return NoState
	},
	// S18
	func(r rune) int {
		switch {
		case r == 61: // ['=','=']
			return 47
		}
		return NoState
	},
	// S19
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 48
		case 65 <= r && r <= 90: // ['A','Z']
			return 49
		case r == 95: // ['_','_']
			return 50
		case 97 <= r && r <= 122: // ['a','z']
			return 49
		}
		return NoState
	},
	// S20
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S21
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S22
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S23
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 48
		case 65 <= r && r <= 90: // ['A','Z']
			return 49
		case r == 95: // ['_','_']
			return 50
		case 97 <= r && r <= 122: // ['a','z']
			return 49
		}
		return NoState
	},
	// S24
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 48
		case 65 <= r && r <= 90: // ['A','Z']
			return 49
		case r == 95: // ['_','_']
			return 50
		case 97 <= r && r <= 100: // ['a','d']
			return 49
		case r == 101: // ['e','e']
			return 51
		case 102 <= r && r <= 122: // ['f','z']
			return 49
		}
		return NoState
	},
	// S25
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 48
		case 65 <= r && r <= 90: // ['A','Z']
			return 49
		case r == 95: // ['_','_']
			return 50
		case r == 97: // ['a','a']
			return 52
		case 98 <= r && r <= 122: // ['b','z']
			return 49
		}
		return NoState
	},
	// S26
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 48
		case 65 <= r && r <= 90: // ['A','Z']
			return 49
		case r == 95: // ['_','_']
			return 50
		case 97 <= r && r <= 114: // ['a','r']
			return 49
		case r == 115: // ['s','s']
			return 53
		case 116 <= r && r <= 122: // ['t','z']
			return 49
		}
		return NoState
	},
	// S27
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 48
		case 65 <= r && r <= 90: // ['A','Z']
			return 49
		case r == 95: // ['_','_']
			return 50
		case 97 <= r && r <= 110: // ['a','n']
			return 49
		case r == 111: // ['o','o']
			return 54
		case 112 <= r && r <= 116: // ['p','t']
			return 49
		case r == 117: // ['u','u']
			return 55
		case 118 <= r && r <= 122: // ['v','z']
			return 49
		}
		return NoState
	},
	// S28
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 48
		case 65 <= r && r <= 90: // ['A','Z']
			return 49
		case r == 95: // ['_','_']
			return 50
		case 97 <= r && r <= 113: // ['a','q']
			return 49
		case r == 114: // ['r','r']
			return 56
		case 115 <= r && r <= 122: // ['s','z']
			return 49
		}
		return NoState
	},
	// S29
	func(r rune) int {
		switch {
		case r == 124: // ['|','|']
			return 57
		}
		return NoState
	},
	// S30
	func(r rune) int {
		switch {
		case r == 61: // ['=','=']
			return 58
		}
		return NoState
	},
	// S31
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S32
	func(r rune) int {
		switch {
		case r == 61: // ['=','=']
			return 59
		}
		return NoState
	},
	// S33
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S34
	func(r rune) int {
		switch {
		case r == 34: // ['"','"']
			return 3
		case r == 92: // ['\','\']
			return 60
		case r == 98: // ['b','b']
			return 60
		case r == 102: // ['f','f']
			return 60
		case r == 110: // ['n','n']
			return 60
		case r == 114: // ['r','r']
			return 60
		case r == 116: // ['t','t']
			return 60
		case r == 117: // ['u','u']
			return 61
		case r == 118: // ['v','v']
			return 60
		case r == 120: // ['x','x']
			return 62
		}
		return NoState
	},
	// S35
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S36
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S37
	func(r rune) int {
		switch {
		case r == 39: // [''',''']
			return 6
		case r == 92: // ['\','\']
			return 63
		case r == 98: // ['b','b']
			return 63
		case r == 102: // ['f','f']
			return 63
		case r == 110: // ['n','n']
			return 63
		case r == 114: // ['r','r']
			return 63
		case r == 116: // ['t','t']
			return 63
		case r == 117: // ['u','u']
			return 64
		case r == 118: // ['v','v']
			return 63
		case r == 120: // ['x','x']
			return 65
		}
		return NoState
	},
	// S38
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 38
		case r == 69: // ['E','E']
			return 66
		case r == 101: // ['e','e']
			return 66
		}
		return NoState
	},
	// S39
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S40
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 67
		case r == 69: // ['E','E']
			return 68
		case r == 101: // ['e','e']
			return 68
		}
		return NoState
	},
	// S41
	func(r rune) int {
		switch {
		case r == 46: // ['.','.']
			return 40
		case 48 <= r && r <= 55: // ['0','7']
			return 41
		case 56 <= r && r <= 57: // ['8','9']
			return 42
		case r == 69: // ['E','E']
			return 43
		case r == 101: // ['e','e']
			return 43
		}
		return NoState
	},
	// S42
	func(r rune) int {
		switch {
		case r == 46: // ['.','.']
			return 40
		case 48 <= r && r <= 57: // ['0','9']
			return 42
		case r == 69: // ['E','E']
			return 43
		case r == 101: // ['e','e']
			return 43
		}
		return NoState
	},
	// S43
	func(r rune) int {
		switch {
		case r == 43: // ['+','+']
			return 69
		case r == 45: // ['-','-']
			return 69
		case 48 <= r && r <= 57: // ['0','9']
			return 70
		}
		return NoState
	},
	// S44
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 71
		case 65 <= r && r <= 70: // ['A','F']
			return 72
		case 97 <= r && r <= 102: // ['a','f']
			return 72
		}
		return NoState
	},
	// S45
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S46
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S47
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S48
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 48
		case 65 <= r && r <= 90: // ['A','Z']
			return 49
		case r == 95: // ['_','_']
			return 50
		case 97 <= r && r <= 122: // ['a','z']
			return 49
		}
		return NoState
	},
	// S49
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 48
		case 65 <= r && r <= 90: // ['A','Z']
			return 49
		case r == 95: // ['_','_']
			return 50
		case 97 <= r && r <= 122: // ['a','z']
			return 49
		}
		return NoState
	},
	// S50
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 48
		case 65 <= r && r <= 90: // ['A','Z']
			return 49
		case r == 95: // ['_','_']
			return 50
		case 97 <= r && r <= 122: // ['a','z']
			return 49
		}
		return NoState
	},
	// S51
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 48
		case 65 <= r && r <= 90: // ['A','Z']
			return 49
		case r == 95: // ['_','_']
			return 50
		case 97 <= r && r <= 101: // ['a','e']
			return 49
		case r == 102: // ['f','f']
			return 73
		case 103 <= r && r <= 122: // ['g','z']
			return 49
		}
		return NoState
	},
	// S52
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 48
		case 65 <= r && r <= 90: // ['A','Z']
			return 49
		case r == 95: // ['_','_']
			return 50
		case 97 <= r && r <= 107: // ['a','k']
			return 49
		case r == 108: // ['l','l']
			return 74
		case 109 <= r && r <= 122: // ['m','z']
			return 49
		}
		return NoState
	},
	// S53
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 48
		case 65 <= r && r <= 90: // ['A','Z']
			return 49
		case r == 95: // ['_','_']
			return 50
		case 97 <= r && r <= 109: // ['a','m']
			return 49
		case r == 110: // ['n','n']
			return 75
		case 111 <= r && r <= 122: // ['o','z']
			return 49
		}
		return NoState
	},
	// S54
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 48
		case 65 <= r && r <= 90: // ['A','Z']
			return 49
		case r == 95: // ['_','_']
			return 50
		case 97 <= r && r <= 115: // ['a','s']
			return 49
		case r == 116: // ['t','t']
			return 76
		case 117 <= r && r <= 122: // ['u','z']
			return 49
		}
		return NoState
	},
	// S55
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 48
		case 65 <= r && r <= 90: // ['A','Z']
			return 49
		case r == 95: // ['_','_']
			return 50
		case 97 <= r && r <= 107: // ['a','k']
			return 49
		case r == 108: // ['l','l']
			return 77
		case 109 <= r && r <= 122: // ['m','z']
			return 49
		}
		return NoState
	},
	// S56
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 48
		case 65 <= r && r <= 90: // ['A','Z']
			return 49
		case r == 95: // ['_','_']
			return 50
		case 97 <= r && r <= 116: // ['a','t']
			return 49
		case r == 117: // ['u','u']
			return 78
		case 118 <= r && r <= 122: // ['v','z']
			return 49
		}
		return NoState
	},
	// S57
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S58
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S59
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S60
	func(r rune) int {
		switch {
		case r == 34: // ['"','"']
			return 33
		case r == 92: // ['\','\']
			return 34
		default:
			return 3
		}
	},
	// S61
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 79
		case 65 <= r && r <= 70: // ['A','F']
			return 80
		case 97 <= r && r <= 102: // ['a','f']
			return 80
		}
		return NoState
	},
	// S62
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 81
		case 65 <= r && r <= 70: // ['A','F']
			return 82
		case 97 <= r && r <= 102: // ['a','f']
			return 82
		}
		return NoState
	},
	// S63
	func(r rune) int {
		switch {
		case r == 39: // [''',''']
			return 36
		case r == 92: // ['\','\']
			return 37
		default:
			return 6
		}
	},
	// S64
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 83
		case 65 <= r && r <= 70: // ['A','F']
			return 84
		case 97 <= r && r <= 102: // ['a','f']
			return 84
		}
		return NoState
	},
	// S65
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 85
		case 65 <= r && r <= 70: // ['A','F']
			return 86
		case 97 <= r && r <= 102: // ['a','f']
			return 86
		}
		return NoState
	},
	// S66
	func(r rune) int {
		switch {
		case r == 43: // ['+','+']
			return 87
		case r == 45: // ['-','-']
			return 87
		case 48 <= r && r <= 57: // ['0','9']
			return 88
		}
		return NoState
	},
	// S67
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 67
		case r == 69: // ['E','E']
			return 68
		case r == 101: // ['e','e']
			return 68
		}
		return NoState
	},
	// S68
	func(r rune) int {
		switch {
		case r == 43: // ['+','+']
			return 89
		case r == 45: // ['-','-']
			return 89
		case 48 <= r && r <= 57: // ['0','9']
			return 90
		}
		return NoState
	},
	// S69
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 70
		}
		return NoState
	},
	// S70
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 70
		}
		return NoState
	},
	// S71
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 71
		case 65 <= r && r <= 70: // ['A','F']
			return 72
		case 97 <= r && r <= 102: // ['a','f']
			return 72
		}
		return NoState
	},
	// S72
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 71
		case 65 <= r && r <= 70: // ['A','F']
			return 72
		case 97 <= r && r <= 102: // ['a','f']
			return 72
		}
		return NoState
	},
	// S73
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 48
		case 65 <= r && r <= 90: // ['A','Z']
			return 49
		case r == 95: // ['_','_']
			return 50
		case 97 <= r && r <= 104: // ['a','h']
			return 49
		case r == 105: // ['i','i']
			return 91
		case 106 <= r && r <= 122: // ['j','z']
			return 49
		}
		return NoState
	},
	// S74
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 48
		case 65 <= r && r <= 90: // ['A','Z']
			return 49
		case r == 95: // ['_','_']
			return 50
		case 97 <= r && r <= 114: // ['a','r']
			return 49
		case r == 115: // ['s','s']
			return 92
		case 116 <= r && r <= 122: // ['t','z']
			return 49
		}
		return NoState
	},
	// S75
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 48
		case 65 <= r && r <= 90: // ['A','Z']
			return 49
		case r == 95: // ['_','_']
			return 50
		case 97 <= r && r <= 110: // ['a','n']
			return 49
		case r == 111: // ['o','o']
			return 93
		case 112 <= r && r <= 122: // ['p','z']
			return 49
		}
		return NoState
	},
	// S76
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 48
		case 65 <= r && r <= 90: // ['A','Z']
			return 49
		case r == 95: // ['_','_']
			return 50
		case 97 <= r && r <= 122: // ['a','z']
			return 49
		}
		return NoState
	},
	// S77
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 48
		case 65 <= r && r <= 90: // ['A','Z']
			return 49
		case r == 95: // ['_','_']
			return 50
		case 97 <= r && r <= 107: // ['a','k']
			return 49
		case r == 108: // ['l','l']
			return 94
		case 109 <= r && r <= 122: // ['m','z']
			return 49
		}
		return NoState
	},
	// S78
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 48
		case 65 <= r && r <= 90: // ['A','Z']
			return 49
		case r == 95: // ['_','_']
			return 50
		case 97 <= r && r <= 100: // ['a','d']
			return 49
		case r == 101: // ['e','e']
			return 95
		case 102 <= r && r <= 122: // ['f','z']
			return 49
		}
		return NoState
	},
	// S79
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 96
		case 65 <= r && r <= 70: // ['A','F']
			return 97
		case 97 <= r && r <= 102: // ['a','f']
			return 97
		}
		return NoState
	},
	// S80
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 96
		case 65 <= r && r <= 70: // ['A','F']
			return 97
		case 97 <= r && r <= 102: // ['a','f']
			return 97
		}
		return NoState
	},
	// S81
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 98
		case 65 <= r && r <= 70: // ['A','F']
			return 99
		case 97 <= r && r <= 102: // ['a','f']
			return 99
		}
		return NoState
	},
	// S82
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 98
		case 65 <= r && r <= 70: // ['A','F']
			return 99
		case 97 <= r && r <= 102: // ['a','f']
			return 99
		}
		return NoState
	},
	// S83
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 100
		case 65 <= r && r <= 70: // ['A','F']
			return 101
		case 97 <= r && r <= 102: // ['a','f']
			return 101
		}
		return NoState
	},
	// S84
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 100
		case 65 <= r && r <= 70: // ['A','F']
			return 101
		case 97 <= r && r <= 102: // ['a','f']
			return 101
		}
		return NoState
	},
	// S85
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 102
		case 65 <= r && r <= 70: // ['A','F']
			return 103
		case 97 <= r && r <= 102: // ['a','f']
			return 103
		}
		return NoState
	},
	// S86
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 102
		case 65 <= r && r <= 70: // ['A','F']
			return 103
		case 97 <= r && r <= 102: // ['a','f']
			return 103
		}
		return NoState
	},
	// S87
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 88
		}
		return NoState
	},
	// S88
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 88
		}
		return NoState
	},
	// S89
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 90
		}
		return NoState
	},
	// S90
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 90
		}
		return NoState
	},
	// S91
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 48
		case 65 <= r && r <= 90: // ['A','Z']
			return 49
		case r == 95: // ['_','_']
			return 50
		case 97 <= r && r <= 109: // ['a','m']
			return 49
		case r == 110: // ['n','n']
			return 104
		case 111 <= r && r <= 122: // ['o','z']
			return 49
		}
		return NoState
	},
	// S92
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 48
		case 65 <= r && r <= 90: // ['A','Z']
			return 49
		case r == 95: // ['_','_']
			return 50
		case 97 <= r && r <= 100: // ['a','d']
			return 49
		case r == 101: // ['e','e']
			return 105
		case 102 <= r && r <= 122: // ['f','z']
			return 49
		}
		return NoState
	},
	// S93
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 48
		case 65 <= r && r <= 90: // ['A','Z']
			return 49
		case r == 95: // ['_','_']
			return 50
		case 97 <= r && r <= 115: // ['a','s']
			return 49
		case r == 116: // ['t','t']
			return 106
		case 117 <= r && r <= 122: // ['u','z']
			return 49
		}
		return NoState
	},
	// S94
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 48
		case 65 <= r && r <= 90: // ['A','Z']
			return 49
		case r == 95: // ['_','_']
			return 50
		case 97 <= r && r <= 122: // ['a','z']
			return 49
		}
		return NoState
	},
	// S95
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 48
		case 65 <= r && r <= 90: // ['A','Z']
			return 49
		case r == 95: // ['_','_']
			return 50
		case 97 <= r && r <= 122: // ['a','z']
			return 49
		}
		return NoState
	},
	// S96
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 107
		case 65 <= r && r <= 70: // ['A','F']
			return 108
		case 97 <= r && r <= 102: // ['a','f']
			return 108
		}
		return NoState
	},
	// S97
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 107
		case 65 <= r && r <= 70: // ['A','F']
			return 108
		case 97 <= r && r <= 102: // ['a','f']
			return 108
		}
		return NoState
	},
	// S98
	func(r rune) int {
		switch {
		case r == 34: // ['"','"']
			return 33
		case r == 92: // ['\','\']
			return 34
		default:
			return 3
		}
	},
	// S99
	func(r rune) int {
		switch {
		case r == 34: // ['"','"']
			return 33
		case r == 92: // ['\','\']
			return 34
		default:
			return 3
		}
	},
	// S100
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 109
		case 65 <= r && r <= 70: // ['A','F']
			return 110
		case 97 <= r && r <= 102: // ['a','f']
			return 110
		}
		return NoState
	},
	// S101
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 109
		case 65 <= r && r <= 70: // ['A','F']
			return 110
		case 97 <= r && r <= 102: // ['a','f']
			return 110
		}
		return NoState
	},
	// S102
	func(r rune) int {
		switch {
		case r == 39: // [''',''']
			return 36
		case r == 92: // ['\','\']
			return 37
		default:
			return 6
		}
	},
	// S103
	func(r rune) int {
		switch {
		case r == 39: // [''',''']
			return 36
		case r == 92: // ['\','\']
			return 37
		default:
			return 6
		}
	},
	// S104
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 48
		case 65 <= r && r <= 90: // ['A','Z']
			return 49
		case r == 95: // ['_','_']
			return 50
		case 97 <= r && r <= 100: // ['a','d']
			return 49
		case r == 101: // ['e','e']
			return 111
		case 102 <= r && r <= 122: // ['f','z']
			return 49
		}
		return NoState
	},
	// S105
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 48
		case 65 <= r && r <= 90: // ['A','Z']
			return 49
		case r == 95: // ['_','_']
			return 50
		case 97 <= r && r <= 122: // ['a','z']
			return 49
		}
		return NoState
	},
	// S106
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 48
		case 65 <= r && r <= 90: // ['A','Z']
			return 49
		case r == 95: // ['_','_']
			return 50
		case 97 <= r && r <= 122: // ['a','z']
			return 49
		}
		return NoState
	},
	// S107
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 112
		case 65 <= r && r <= 70: // ['A','F']
			return 113
		case 97 <= r && r <= 102: // ['a','f']
			return 113
		}
		return NoState
	},
	// S108
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 112
		case 65 <= r && r <= 70: // ['A','F']
			return 113
		case 97 <= r && r <= 102: // ['a','f']
			return 113
		}
		return NoState
	},
	// S109
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 114
		case 65 <= r && r <= 70: // ['A','F']
			return 115
		case 97 <= r && r <= 102: // ['a','f']
			return 115
		}
		return NoState
	},
	// S110
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 114
		case 65 <= r && r <= 70: // ['A','F']
			return 115
		case 97 <= r && r <= 102: // ['a','f']
			return 115
		}
		return NoState
	},
	// S111
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 48
		case 65 <= r && r <= 90: // ['A','Z']
			return 49
		case r == 95: // ['_','_']
			return 50
		case 97 <= r && r <= 99: // ['a','c']
			return 49
		case r == 100: // ['d','d']
			return 116
		case 101 <= r && r <= 122: // ['e','z']
			return 49
		}
		return NoState
	},
	// S112
	func(r rune) int {
		switch {
		case r == 34: // ['"','"']
			return 33
		case r == 92: // ['\','\']
			return 34
		default:
			return 3
		}
	},
	// S113
	func(r rune) int {
		switch {
		case r == 34: // ['"','"']
			return 33
		case r == 92: // ['\','\']
			return 34
		default:
			return 3
		}
	},
	// S114
	func(r rune) int {
		switch {
		case r == 39: // [''',''']
			return 36
		case r == 92: // ['\','\']
			return 37
		default:
			return 6
		}
	},
	// S115
	func(r rune) int {
		switch {
		case r == 39: // [''',''']
			return 36
		case r == 92: // ['\','\']
			return 37
		default:
			return 6
		}
	},
	// S116
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 48
		case 65 <= r && r <= 90: // ['A','Z']
			return 49
		case r == 95: // ['_','_']
			return 50
		case 97 <= r && r <= 122: // ['a','z']
			return 49
		}
		return NoState
	},
}
