// Code generated by gocc; DO NOT EDIT.

package parser

type (
	actionTable [numStates]actionRow
	actionRow   struct {
		canRecover bool
		actions    [numSymbols]action
	}
)

var actionTab = actionTable{
	actionRow{ // S0
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* ^ */
			shift(4),  /* - */
			shift(5),  /* ! */
			shift(9),  /* null */
			shift(11), /* true */
			shift(12), /* false */
			shift(14), /* intLit */
			shift(15), /* floatLit */
			shift(17), /* doubleStringLit */
			shift(18), /* singleStringLit */
			shift(20), /* symbol */
			nil,       /* . */
			nil,       /* [ */
			nil,       /* ] */
		},
	},
	actionRow{ // S1
		canRecover: false,
		actions: [numSymbols]action{
			nil,          /* INVALID */
			accept(true), /* $ */
			shift(21),    /* ^ */
			nil,          /* - */
			nil,          /* ! */
			nil,          /* null */
			nil,          /* true */
			nil,          /* false */
			nil,          /* intLit */
			nil,          /* floatLit */
			nil,          /* doubleStringLit */
			nil,          /* singleStringLit */
			nil,          /* symbol */
			nil,          /* . */
			nil,          /* [ */
			nil,          /* ] */
		},
	},
	actionRow{ // S2
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			reduce(1), /* $, reduce: ExpExpr */
			reduce(1), /* ^, reduce: ExpExpr */
			nil,       /* - */
			nil,       /* ! */
			nil,       /* null */
			nil,       /* true */
			nil,       /* false */
			nil,       /* intLit */
			nil,       /* floatLit */
			nil,       /* doubleStringLit */
			nil,       /* singleStringLit */
			nil,       /* symbol */
			nil,       /* . */
			nil,       /* [ */
			nil,       /* ] */
		},
	},
	actionRow{ // S3
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			reduce(3), /* $, reduce: UnaryExpr */
			reduce(3), /* ^, reduce: UnaryExpr */
			nil,       /* - */
			nil,       /* ! */
			nil,       /* null */
			nil,       /* true */
			nil,       /* false */
			nil,       /* intLit */
			nil,       /* floatLit */
			nil,       /* doubleStringLit */
			nil,       /* singleStringLit */
			nil,       /* symbol */
			nil,       /* . */
			nil,       /* [ */
			nil,       /* ] */
		},
	},
	actionRow{ // S4
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* ^ */
			nil,       /* - */
			nil,       /* ! */
			shift(9),  /* null */
			shift(11), /* true */
			shift(12), /* false */
			shift(14), /* intLit */
			shift(15), /* floatLit */
			shift(17), /* doubleStringLit */
			shift(18), /* singleStringLit */
			shift(20), /* symbol */
			nil,       /* . */
			nil,       /* [ */
			nil,       /* ] */
		},
	},
	actionRow{ // S5
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* ^ */
			shift(4),  /* - */
			shift(5),  /* ! */
			shift(9),  /* null */
			shift(11), /* true */
			shift(12), /* false */
			shift(14), /* intLit */
			shift(15), /* floatLit */
			shift(17), /* doubleStringLit */
			shift(18), /* singleStringLit */
			shift(20), /* symbol */
			nil,       /* . */
			nil,       /* [ */
			nil,       /* ] */
		},
	},
	actionRow{ // S6
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			reduce(6), /* $, reduce: Expr */
			reduce(6), /* ^, reduce: Expr */
			nil,       /* - */
			nil,       /* ! */
			nil,       /* null */
			nil,       /* true */
			nil,       /* false */
			nil,       /* intLit */
			nil,       /* floatLit */
			nil,       /* doubleStringLit */
			nil,       /* singleStringLit */
			nil,       /* symbol */
			nil,       /* . */
			nil,       /* [ */
			nil,       /* ] */
		},
	},
	actionRow{ // S7
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			reduce(7), /* $, reduce: Expr */
			reduce(7), /* ^, reduce: Expr */
			nil,       /* - */
			nil,       /* ! */
			nil,       /* null */
			nil,       /* true */
			nil,       /* false */
			nil,       /* intLit */
			nil,       /* floatLit */
			nil,       /* doubleStringLit */
			nil,       /* singleStringLit */
			nil,       /* symbol */
			shift(24), /* . */
			shift(25), /* [ */
			nil,       /* ] */
		},
	},
	actionRow{ // S8
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			reduce(15), /* $, reduce: Literal */
			reduce(15), /* ^, reduce: Literal */
			nil,        /* - */
			nil,        /* ! */
			nil,        /* null */
			nil,        /* true */
			nil,        /* false */
			nil,        /* intLit */
			nil,        /* floatLit */
			nil,        /* doubleStringLit */
			nil,        /* singleStringLit */
			nil,        /* symbol */
			nil,        /* . */
			nil,        /* [ */
			nil,        /* ] */
		},
	},
	actionRow{ // S9
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			reduce(8), /* $, reduce: NullLiteral */
			reduce(8), /* ^, reduce: NullLiteral */
			nil,       /* - */
			nil,       /* ! */
			nil,       /* null */
			nil,       /* true */
			nil,       /* false */
			nil,       /* intLit */
			nil,       /* floatLit */
			nil,       /* doubleStringLit */
			nil,       /* singleStringLit */
			nil,       /* symbol */
			nil,       /* . */
			nil,       /* [ */
			nil,       /* ] */
		},
	},
	actionRow{ // S10
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			reduce(16), /* $, reduce: Literal */
			reduce(16), /* ^, reduce: Literal */
			nil,        /* - */
			nil,        /* ! */
			nil,        /* null */
			nil,        /* true */
			nil,        /* false */
			nil,        /* intLit */
			nil,        /* floatLit */
			nil,        /* doubleStringLit */
			nil,        /* singleStringLit */
			nil,        /* symbol */
			nil,        /* . */
			nil,        /* [ */
			nil,        /* ] */
		},
	},
	actionRow{ // S11
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			reduce(9), /* $, reduce: BooleanLiteral */
			reduce(9), /* ^, reduce: BooleanLiteral */
			nil,       /* - */
			nil,       /* ! */
			nil,       /* null */
			nil,       /* true */
			nil,       /* false */
			nil,       /* intLit */
			nil,       /* floatLit */
			nil,       /* doubleStringLit */
			nil,       /* singleStringLit */
			nil,       /* symbol */
			nil,       /* . */
			nil,       /* [ */
			nil,       /* ] */
		},
	},
	actionRow{ // S12
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			reduce(10), /* $, reduce: BooleanLiteral */
			reduce(10), /* ^, reduce: BooleanLiteral */
			nil,        /* - */
			nil,        /* ! */
			nil,        /* null */
			nil,        /* true */
			nil,        /* false */
			nil,        /* intLit */
			nil,        /* floatLit */
			nil,        /* doubleStringLit */
			nil,        /* singleStringLit */
			nil,        /* symbol */
			nil,        /* . */
			nil,        /* [ */
			nil,        /* ] */
		},
	},
	actionRow{ // S13
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			reduce(17), /* $, reduce: Literal */
			reduce(17), /* ^, reduce: Literal */
			nil,        /* - */
			nil,        /* ! */
			nil,        /* null */
			nil,        /* true */
			nil,        /* false */
			nil,        /* intLit */
			nil,        /* floatLit */
			nil,        /* doubleStringLit */
			nil,        /* singleStringLit */
			nil,        /* symbol */
			nil,        /* . */
			nil,        /* [ */
			nil,        /* ] */
		},
	},
	actionRow{ // S14
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			reduce(11), /* $, reduce: NumericLiteral */
			reduce(11), /* ^, reduce: NumericLiteral */
			nil,        /* - */
			nil,        /* ! */
			nil,        /* null */
			nil,        /* true */
			nil,        /* false */
			nil,        /* intLit */
			nil,        /* floatLit */
			nil,        /* doubleStringLit */
			nil,        /* singleStringLit */
			nil,        /* symbol */
			nil,        /* . */
			nil,        /* [ */
			nil,        /* ] */
		},
	},
	actionRow{ // S15
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			reduce(12), /* $, reduce: NumericLiteral */
			reduce(12), /* ^, reduce: NumericLiteral */
			nil,        /* - */
			nil,        /* ! */
			nil,        /* null */
			nil,        /* true */
			nil,        /* false */
			nil,        /* intLit */
			nil,        /* floatLit */
			nil,        /* doubleStringLit */
			nil,        /* singleStringLit */
			nil,        /* symbol */
			nil,        /* . */
			nil,        /* [ */
			nil,        /* ] */
		},
	},
	actionRow{ // S16
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			reduce(18), /* $, reduce: Literal */
			reduce(18), /* ^, reduce: Literal */
			nil,        /* - */
			nil,        /* ! */
			nil,        /* null */
			nil,        /* true */
			nil,        /* false */
			nil,        /* intLit */
			nil,        /* floatLit */
			nil,        /* doubleStringLit */
			nil,        /* singleStringLit */
			nil,        /* symbol */
			nil,        /* . */
			nil,        /* [ */
			nil,        /* ] */
		},
	},
	actionRow{ // S17
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			reduce(13), /* $, reduce: StringLiteral */
			reduce(13), /* ^, reduce: StringLiteral */
			nil,        /* - */
			nil,        /* ! */
			nil,        /* null */
			nil,        /* true */
			nil,        /* false */
			nil,        /* intLit */
			nil,        /* floatLit */
			nil,        /* doubleStringLit */
			nil,        /* singleStringLit */
			nil,        /* symbol */
			nil,        /* . */
			nil,        /* [ */
			nil,        /* ] */
		},
	},
	actionRow{ // S18
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			reduce(14), /* $, reduce: StringLiteral */
			reduce(14), /* ^, reduce: StringLiteral */
			nil,        /* - */
			nil,        /* ! */
			nil,        /* null */
			nil,        /* true */
			nil,        /* false */
			nil,        /* intLit */
			nil,        /* floatLit */
			nil,        /* doubleStringLit */
			nil,        /* singleStringLit */
			nil,        /* symbol */
			nil,        /* . */
			nil,        /* [ */
			nil,        /* ] */
		},
	},
	actionRow{ // S19
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			reduce(20), /* $, reduce: Identifier */
			reduce(20), /* ^, reduce: Identifier */
			nil,        /* - */
			nil,        /* ! */
			nil,        /* null */
			nil,        /* true */
			nil,        /* false */
			nil,        /* intLit */
			nil,        /* floatLit */
			nil,        /* doubleStringLit */
			nil,        /* singleStringLit */
			nil,        /* symbol */
			reduce(20), /* ., reduce: Identifier */
			reduce(20), /* [, reduce: Identifier */
			nil,        /* ] */
		},
	},
	actionRow{ // S20
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			reduce(19), /* $, reduce: ObjectKey */
			reduce(19), /* ^, reduce: ObjectKey */
			nil,        /* - */
			nil,        /* ! */
			nil,        /* null */
			nil,        /* true */
			nil,        /* false */
			nil,        /* intLit */
			nil,        /* floatLit */
			nil,        /* doubleStringLit */
			nil,        /* singleStringLit */
			nil,        /* symbol */
			reduce(19), /* ., reduce: ObjectKey */
			reduce(19), /* [, reduce: ObjectKey */
			nil,        /* ] */
		},
	},
	actionRow{ // S21
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* ^ */
			shift(4),  /* - */
			shift(5),  /* ! */
			shift(9),  /* null */
			shift(11), /* true */
			shift(12), /* false */
			shift(14), /* intLit */
			shift(15), /* floatLit */
			shift(17), /* doubleStringLit */
			shift(18), /* singleStringLit */
			shift(20), /* symbol */
			nil,       /* . */
			nil,       /* [ */
			nil,       /* ] */
		},
	},
	actionRow{ // S22
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			reduce(4), /* $, reduce: UnaryExpr */
			reduce(4), /* ^, reduce: UnaryExpr */
			nil,       /* - */
			nil,       /* ! */
			nil,       /* null */
			nil,       /* true */
			nil,       /* false */
			nil,       /* intLit */
			nil,       /* floatLit */
			nil,       /* doubleStringLit */
			nil,       /* singleStringLit */
			nil,       /* symbol */
			nil,       /* . */
			nil,       /* [ */
			nil,       /* ] */
		},
	},
	actionRow{ // S23
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			reduce(5), /* $, reduce: UnaryExpr */
			reduce(5), /* ^, reduce: UnaryExpr */
			nil,       /* - */
			nil,       /* ! */
			nil,       /* null */
			nil,       /* true */
			nil,       /* false */
			nil,       /* intLit */
			nil,       /* floatLit */
			nil,       /* doubleStringLit */
			nil,       /* singleStringLit */
			nil,       /* symbol */
			nil,       /* . */
			nil,       /* [ */
			nil,       /* ] */
		},
	},
	actionRow{ // S24
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* ^ */
			nil,       /* - */
			nil,       /* ! */
			nil,       /* null */
			nil,       /* true */
			nil,       /* false */
			nil,       /* intLit */
			nil,       /* floatLit */
			nil,       /* doubleStringLit */
			nil,       /* singleStringLit */
			shift(20), /* symbol */
			nil,       /* . */
			nil,       /* [ */
			nil,       /* ] */
		},
	},
	actionRow{ // S25
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* ^ */
			nil,       /* - */
			nil,       /* ! */
			shift(32), /* null */
			shift(34), /* true */
			shift(35), /* false */
			shift(37), /* intLit */
			shift(38), /* floatLit */
			shift(40), /* doubleStringLit */
			shift(41), /* singleStringLit */
			shift(43), /* symbol */
			nil,       /* . */
			nil,       /* [ */
			nil,       /* ] */
		},
	},
	actionRow{ // S26
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			reduce(2), /* $, reduce: ExpExpr */
			reduce(2), /* ^, reduce: ExpExpr */
			nil,       /* - */
			nil,       /* ! */
			nil,       /* null */
			nil,       /* true */
			nil,       /* false */
			nil,       /* intLit */
			nil,       /* floatLit */
			nil,       /* doubleStringLit */
			nil,       /* singleStringLit */
			nil,       /* symbol */
			nil,       /* . */
			nil,       /* [ */
			nil,       /* ] */
		},
	},
	actionRow{ // S27
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			reduce(21), /* $, reduce: Identifier */
			reduce(21), /* ^, reduce: Identifier */
			nil,        /* - */
			nil,        /* ! */
			nil,        /* null */
			nil,        /* true */
			nil,        /* false */
			nil,        /* intLit */
			nil,        /* floatLit */
			nil,        /* doubleStringLit */
			nil,        /* singleStringLit */
			nil,        /* symbol */
			reduce(21), /* ., reduce: Identifier */
			reduce(21), /* [, reduce: Identifier */
			nil,        /* ] */
		},
	},
	actionRow{ // S28
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* ^ */
			nil,       /* - */
			nil,       /* ! */
			nil,       /* null */
			nil,       /* true */
			nil,       /* false */
			nil,       /* intLit */
			nil,       /* floatLit */
			nil,       /* doubleStringLit */
			nil,       /* singleStringLit */
			nil,       /* symbol */
			nil,       /* . */
			nil,       /* [ */
			shift(44), /* ] */
		},
	},
	actionRow{ // S29
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* ^ */
			nil,       /* - */
			nil,       /* ! */
			nil,       /* null */
			nil,       /* true */
			nil,       /* false */
			nil,       /* intLit */
			nil,       /* floatLit */
			nil,       /* doubleStringLit */
			nil,       /* singleStringLit */
			nil,       /* symbol */
			nil,       /* . */
			nil,       /* [ */
			reduce(6), /* ], reduce: Expr */
		},
	},
	actionRow{ // S30
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* ^ */
			nil,       /* - */
			nil,       /* ! */
			nil,       /* null */
			nil,       /* true */
			nil,       /* false */
			nil,       /* intLit */
			nil,       /* floatLit */
			nil,       /* doubleStringLit */
			nil,       /* singleStringLit */
			nil,       /* symbol */
			shift(45), /* . */
			shift(46), /* [ */
			reduce(7), /* ], reduce: Expr */
		},
	},
	actionRow{ // S31
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* ^ */
			nil,        /* - */
			nil,        /* ! */
			nil,        /* null */
			nil,        /* true */
			nil,        /* false */
			nil,        /* intLit */
			nil,        /* floatLit */
			nil,        /* doubleStringLit */
			nil,        /* singleStringLit */
			nil,        /* symbol */
			nil,        /* . */
			nil,        /* [ */
			reduce(15), /* ], reduce: Literal */
		},
	},
	actionRow{ // S32
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* ^ */
			nil,       /* - */
			nil,       /* ! */
			nil,       /* null */
			nil,       /* true */
			nil,       /* false */
			nil,       /* intLit */
			nil,       /* floatLit */
			nil,       /* doubleStringLit */
			nil,       /* singleStringLit */
			nil,       /* symbol */
			nil,       /* . */
			nil,       /* [ */
			reduce(8), /* ], reduce: NullLiteral */
		},
	},
	actionRow{ // S33
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* ^ */
			nil,        /* - */
			nil,        /* ! */
			nil,        /* null */
			nil,        /* true */
			nil,        /* false */
			nil,        /* intLit */
			nil,        /* floatLit */
			nil,        /* doubleStringLit */
			nil,        /* singleStringLit */
			nil,        /* symbol */
			nil,        /* . */
			nil,        /* [ */
			reduce(16), /* ], reduce: Literal */
		},
	},
	actionRow{ // S34
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* ^ */
			nil,       /* - */
			nil,       /* ! */
			nil,       /* null */
			nil,       /* true */
			nil,       /* false */
			nil,       /* intLit */
			nil,       /* floatLit */
			nil,       /* doubleStringLit */
			nil,       /* singleStringLit */
			nil,       /* symbol */
			nil,       /* . */
			nil,       /* [ */
			reduce(9), /* ], reduce: BooleanLiteral */
		},
	},
	actionRow{ // S35
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* ^ */
			nil,        /* - */
			nil,        /* ! */
			nil,        /* null */
			nil,        /* true */
			nil,        /* false */
			nil,        /* intLit */
			nil,        /* floatLit */
			nil,        /* doubleStringLit */
			nil,        /* singleStringLit */
			nil,        /* symbol */
			nil,        /* . */
			nil,        /* [ */
			reduce(10), /* ], reduce: BooleanLiteral */
		},
	},
	actionRow{ // S36
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* ^ */
			nil,        /* - */
			nil,        /* ! */
			nil,        /* null */
			nil,        /* true */
			nil,        /* false */
			nil,        /* intLit */
			nil,        /* floatLit */
			nil,        /* doubleStringLit */
			nil,        /* singleStringLit */
			nil,        /* symbol */
			nil,        /* . */
			nil,        /* [ */
			reduce(17), /* ], reduce: Literal */
		},
	},
	actionRow{ // S37
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* ^ */
			nil,        /* - */
			nil,        /* ! */
			nil,        /* null */
			nil,        /* true */
			nil,        /* false */
			nil,        /* intLit */
			nil,        /* floatLit */
			nil,        /* doubleStringLit */
			nil,        /* singleStringLit */
			nil,        /* symbol */
			nil,        /* . */
			nil,        /* [ */
			reduce(11), /* ], reduce: NumericLiteral */
		},
	},
	actionRow{ // S38
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* ^ */
			nil,        /* - */
			nil,        /* ! */
			nil,        /* null */
			nil,        /* true */
			nil,        /* false */
			nil,        /* intLit */
			nil,        /* floatLit */
			nil,        /* doubleStringLit */
			nil,        /* singleStringLit */
			nil,        /* symbol */
			nil,        /* . */
			nil,        /* [ */
			reduce(12), /* ], reduce: NumericLiteral */
		},
	},
	actionRow{ // S39
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* ^ */
			nil,        /* - */
			nil,        /* ! */
			nil,        /* null */
			nil,        /* true */
			nil,        /* false */
			nil,        /* intLit */
			nil,        /* floatLit */
			nil,        /* doubleStringLit */
			nil,        /* singleStringLit */
			nil,        /* symbol */
			nil,        /* . */
			nil,        /* [ */
			reduce(18), /* ], reduce: Literal */
		},
	},
	actionRow{ // S40
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* ^ */
			nil,        /* - */
			nil,        /* ! */
			nil,        /* null */
			nil,        /* true */
			nil,        /* false */
			nil,        /* intLit */
			nil,        /* floatLit */
			nil,        /* doubleStringLit */
			nil,        /* singleStringLit */
			nil,        /* symbol */
			nil,        /* . */
			nil,        /* [ */
			reduce(13), /* ], reduce: StringLiteral */
		},
	},
	actionRow{ // S41
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* ^ */
			nil,        /* - */
			nil,        /* ! */
			nil,        /* null */
			nil,        /* true */
			nil,        /* false */
			nil,        /* intLit */
			nil,        /* floatLit */
			nil,        /* doubleStringLit */
			nil,        /* singleStringLit */
			nil,        /* symbol */
			nil,        /* . */
			nil,        /* [ */
			reduce(14), /* ], reduce: StringLiteral */
		},
	},
	actionRow{ // S42
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* ^ */
			nil,        /* - */
			nil,        /* ! */
			nil,        /* null */
			nil,        /* true */
			nil,        /* false */
			nil,        /* intLit */
			nil,        /* floatLit */
			nil,        /* doubleStringLit */
			nil,        /* singleStringLit */
			nil,        /* symbol */
			reduce(20), /* ., reduce: Identifier */
			reduce(20), /* [, reduce: Identifier */
			reduce(20), /* ], reduce: Identifier */
		},
	},
	actionRow{ // S43
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* ^ */
			nil,        /* - */
			nil,        /* ! */
			nil,        /* null */
			nil,        /* true */
			nil,        /* false */
			nil,        /* intLit */
			nil,        /* floatLit */
			nil,        /* doubleStringLit */
			nil,        /* singleStringLit */
			nil,        /* symbol */
			reduce(19), /* ., reduce: ObjectKey */
			reduce(19), /* [, reduce: ObjectKey */
			reduce(19), /* ], reduce: ObjectKey */
		},
	},
	actionRow{ // S44
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			reduce(22), /* $, reduce: Identifier */
			reduce(22), /* ^, reduce: Identifier */
			nil,        /* - */
			nil,        /* ! */
			nil,        /* null */
			nil,        /* true */
			nil,        /* false */
			nil,        /* intLit */
			nil,        /* floatLit */
			nil,        /* doubleStringLit */
			nil,        /* singleStringLit */
			nil,        /* symbol */
			reduce(22), /* ., reduce: Identifier */
			reduce(22), /* [, reduce: Identifier */
			nil,        /* ] */
		},
	},
	actionRow{ // S45
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* ^ */
			nil,       /* - */
			nil,       /* ! */
			nil,       /* null */
			nil,       /* true */
			nil,       /* false */
			nil,       /* intLit */
			nil,       /* floatLit */
			nil,       /* doubleStringLit */
			nil,       /* singleStringLit */
			shift(43), /* symbol */
			nil,       /* . */
			nil,       /* [ */
			nil,       /* ] */
		},
	},
	actionRow{ // S46
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* ^ */
			nil,       /* - */
			nil,       /* ! */
			shift(32), /* null */
			shift(34), /* true */
			shift(35), /* false */
			shift(37), /* intLit */
			shift(38), /* floatLit */
			shift(40), /* doubleStringLit */
			shift(41), /* singleStringLit */
			shift(43), /* symbol */
			nil,       /* . */
			nil,       /* [ */
			nil,       /* ] */
		},
	},
	actionRow{ // S47
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* ^ */
			nil,        /* - */
			nil,        /* ! */
			nil,        /* null */
			nil,        /* true */
			nil,        /* false */
			nil,        /* intLit */
			nil,        /* floatLit */
			nil,        /* doubleStringLit */
			nil,        /* singleStringLit */
			nil,        /* symbol */
			reduce(21), /* ., reduce: Identifier */
			reduce(21), /* [, reduce: Identifier */
			reduce(21), /* ], reduce: Identifier */
		},
	},
	actionRow{ // S48
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* ^ */
			nil,       /* - */
			nil,       /* ! */
			nil,       /* null */
			nil,       /* true */
			nil,       /* false */
			nil,       /* intLit */
			nil,       /* floatLit */
			nil,       /* doubleStringLit */
			nil,       /* singleStringLit */
			nil,       /* symbol */
			nil,       /* . */
			nil,       /* [ */
			shift(49), /* ] */
		},
	},
	actionRow{ // S49
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* ^ */
			nil,        /* - */
			nil,        /* ! */
			nil,        /* null */
			nil,        /* true */
			nil,        /* false */
			nil,        /* intLit */
			nil,        /* floatLit */
			nil,        /* doubleStringLit */
			nil,        /* singleStringLit */
			nil,        /* symbol */
			reduce(22), /* ., reduce: Identifier */
			reduce(22), /* [, reduce: Identifier */
			reduce(22), /* ], reduce: Identifier */
		},
	},
}
