// Code generated by gocc; DO NOT EDIT.

package parser

const numNTSymbols = 7

type (
	gotoTable [numStates]gotoRow
	gotoRow   [numNTSymbols]int
)

var gotoTab = gotoTable{
	gotoRow{ // S0
		-1, // S'
		1,  // Expr
		3,  // NullLiteral
		5,  // BooleanLiteral
		8,  // NumericLiteral
		11, // StringLiteral
		2,  // Literal
	},
	gotoRow{ // S1
		-1, // S'
		-1, // Expr
		-1, // NullLiteral
		-1, // BooleanLiteral
		-1, // NumericLiteral
		-1, // StringLiteral
		-1, // Literal
	},
	gotoRow{ // S2
		-1, // S'
		-1, // Expr
		-1, // NullLiteral
		-1, // BooleanLiteral
		-1, // NumericLiteral
		-1, // StringLiteral
		-1, // Literal
	},
	gotoRow{ // S3
		-1, // S'
		-1, // Expr
		-1, // NullLiteral
		-1, // BooleanLiteral
		-1, // NumericLiteral
		-1, // StringLiteral
		-1, // Literal
	},
	gotoRow{ // S4
		-1, // S'
		-1, // Expr
		-1, // NullLiteral
		-1, // BooleanLiteral
		-1, // NumericLiteral
		-1, // StringLiteral
		-1, // Literal
	},
	gotoRow{ // S5
		-1, // S'
		-1, // Expr
		-1, // NullLiteral
		-1, // BooleanLiteral
		-1, // NumericLiteral
		-1, // StringLiteral
		-1, // Literal
	},
	gotoRow{ // S6
		-1, // S'
		-1, // Expr
		-1, // NullLiteral
		-1, // BooleanLiteral
		-1, // NumericLiteral
		-1, // StringLiteral
		-1, // Literal
	},
	gotoRow{ // S7
		-1, // S'
		-1, // Expr
		-1, // NullLiteral
		-1, // BooleanLiteral
		-1, // NumericLiteral
		-1, // StringLiteral
		-1, // Literal
	},
	gotoRow{ // S8
		-1, // S'
		-1, // Expr
		-1, // NullLiteral
		-1, // BooleanLiteral
		-1, // NumericLiteral
		-1, // StringLiteral
		-1, // Literal
	},
	gotoRow{ // S9
		-1, // S'
		-1, // Expr
		-1, // NullLiteral
		-1, // BooleanLiteral
		-1, // NumericLiteral
		-1, // StringLiteral
		-1, // Literal
	},
	gotoRow{ // S10
		-1, // S'
		-1, // Expr
		-1, // NullLiteral
		-1, // BooleanLiteral
		-1, // NumericLiteral
		-1, // StringLiteral
		-1, // Literal
	},
	gotoRow{ // S11
		-1, // S'
		-1, // Expr
		-1, // NullLiteral
		-1, // BooleanLiteral
		-1, // NumericLiteral
		-1, // StringLiteral
		-1, // Literal
	},
	gotoRow{ // S12
		-1, // S'
		-1, // Expr
		-1, // NullLiteral
		-1, // BooleanLiteral
		-1, // NumericLiteral
		-1, // StringLiteral
		-1, // Literal
	},
	gotoRow{ // S13
		-1, // S'
		-1, // Expr
		-1, // NullLiteral
		-1, // BooleanLiteral
		-1, // NumericLiteral
		-1, // StringLiteral
		-1, // Literal
	},
}
